import MobileFooter from "@/components/footer/mobile-footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FanFundr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={`mb-16 ${inter.className}`}>
        <Header />
        {children}
        <MobileFooter />
      </body>
    </html>
  );
}
